### ISSUE TITLE
Missing entry point in package

### ISSUE THREAD

**Issue by nguyentoanit** [arnaud-zg/http-response-status#305]
Hi,

Thanks for making a great package.
But It looks like have a bug from v1.0.30

You can initialize new project and see `./node_modules/http-response-status` folder.
```
npm i http-response-status
```

I couldn't find out an entry point in `node_modules`.
![image](https://user-images.githubusercontent.com/19872073/175447283-36c5a195-8f90-4484-b000-f4ae8a96ae9a.png)

Environment:
```
Node.js: 14.x
```

Thanks for your support. 🥇

**Comment by nguyentoanit** [comment]
Probably, you forgot to add a build step in release CI.

I have created a PR to solve them here (https://github.com/arnaud-zg/http-response-status/pull/306).

**Comment by moltar** [comment]
> Probably, you forgot to add a build step in release CI.
> 
> I have created a PR to solve them here (#306).

Nice one :+1:

**Comment by arnaud-zg** [comment]
Thanks a lot for the fix ❤️

**Comment by arnaud-zg** [comment]
It should be good, I just published a new version `http-response-status@1.1.1`
![image](https://user-images.githubusercontent.com/10991546/175533869-e4882e81-8a60-4a66-898d-2f04722f7b6c.png)
